aplicaciones/base_principal/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasBasePrincipal


app_name ="base_principal"

urlpatterns = [
    

    
    path('', vistasBasePrincipal.Index.as_view() ,name="index"),




    #Para las apis
    #path('probando/', views.Probando ,name="probando"),
    #path('api_login/', views.api_login ,name="api_login"),

    
    
    
] 

aplicaciones/login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as vistasLogin

app_name ="login"

urlpatterns = [
    

    
    path('login/', vistasLogin.Login.as_view() ,name="login"),
    path('logout/', vistasLogin.Logout.as_view() ,name="logout"),
    




    #Para las apis
    #path('probando/', views.Probando ,name="probando"),
    #path('api_login/', views.api_login ,name="api_login"),

    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/usuarios/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views as VistasUsuario

app_name ="usuarios"

urlpatterns = [


    path('perfil', VistasUsuario.Perfil_Usuario.as_view(), name='perfil'),
    path('registrarPaciente', VistasUsuario.registrarUsuarioPaciente, name='registrarUsuarioPaciente'),
    path('registrarProfesional', VistasUsuario.registrarUsuarioProfesional, name='registrarUsuarioProfesional'),
    path('registrarUsuario', VistasUsuario.registrarUsuario, name='registrarUsuario'),
    path('listar usuarios', VistasUsuario.UsuariosListView.as_view(), name='listaUsuarios'),
    #path('login/', vistasLogin.Login.as_view() ,name="login"),
    
    #path('', views.index.as_view() ,name="index"),



    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hicast/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('aplicaciones.base_principal.urls')),
    path('', include(('aplicaciones.login.urls'))),
    path('', include(('aplicaciones.usuarios.urls'))),
]

aplicaciones/base_principal/models.py
from django.db import models

# Create your models here.

aplicaciones/base_principal/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
#Estos dos modelos son para crear permisos personalizados
from django.contrib.auth.models import Permission,Group



#Clases para las plantillas
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView

#Para las fechas
from datetime import datetime





class Index(TemplateView):

    #Esta en base_principal
    #template_name = "index.html"
    template_name = "index-hicast.html"

    def dispatch(self, request, *args, **kwargs):

        if request.user.is_anonymous:
            print("No estas autenticado, eres un usuario anonimo")
            return redirect("login:login")

        else:

            print("Estas autenticado GENIAL")
            #print("Permisos: ",list(Permission.objects.all()))
            print("usuario: ",request.user," Cantidad de Grupos: ",Group.objects.all().count())

            #GCliente = Group.objects.get(name="cliente_E")

            print("\n\n")
            #print("\n\nPermisos Grupo Productor: ",GProductor.permissions.all() )
            #for elemento in GCliente.permissions.all():
            #    print(elemento.name)
            #print("\n\n")

            #Grupo_productor.permissions.set(Permission.objects.get(name="Can add inventario"),
            print("administrador:",request.user.groups.filter(name='administrador').exists())
            print("productor:",request.user.groups.filter(name='productor').exists())
            print("cliente :",request.user.groups.filter(name='cliente').exists())
            print("\n\n")
            



        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."


        return context

aplicaciones/base_principal/templates/index-hicast.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/css/bootstrap4-toggle.min.css"
    rel="stylesheet">
  <title>SISTEMA HICAST</title>
</head>
<body>
  <body style="background-color: #a2dcf0;"></body>
  <div class="container">
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand">HICAST</a>
      
      
        {% if user.is_authenticated %}

            <div id="areaLogin">
                <a class="link-light" href="{% url 'usuarios:registrarUsuarioPaciente' %}"><button id="btnCerrar" type="button" class="btn btn-success" href="dsd">Registrar Pacientes</button></a>
                <a class="link-light" href="{% url 'login:logout' %}"><button id="btnCerrar" type="button" class="btn btn-success" href="dsd">Registrar Profesionales</button></a>
                <a class="link-light" href="{% url 'login:logout' %}"><button id="btnCerrar" type="button" class="btn btn-success" href="dsd">Registrar Usuarios</button></a>
                <a class="link-light" href="{% url 'login:logout' %}"><button id="btnCerrar" type="button" class="btn btn-danger" href="dsd">Cerrar sesion</button></a>
            </div>

        {% else %}

            <div class="form-inline">
                <div class="custom-control custom-checkbox my-1 mr-sm-2" id="checkLogin">
                <input type="checkbox" checked data-toggle="toggle" data-on="Registrarse" data-off="Ingresar" id="loginRestro" >
            </div>

            <div id="areaRegistro" style="display: none;">
                <input type="email" id="email" placeholder="Registra tu correo" class="form-control mr-sm-2" />
                <input type="password" id="pass" placeholder="Registra tu password" class="form-control mr-sm-2" />
                <button onclick="enviar()" class="btn btn-outline-success my-2 my-sm-0">Registro</button>
            </div>
            <div id="areaLogin" style="display: none;">
                <form action="{% url 'login:login' %}" method="post" encoding='utf-8'>
                    {% csrf_token %}
                    
                    {{form.username}}
                    {{form.password}}
                <button type="submit" id="" class="btn btn-outline-success my-2 my-sm-0">Acceso</button>
                    <!--<button onclick="acceso()" id="btnSiguiente" style="background-color: #1b8a40; border: none; color: white; padding: 10px 20px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer;" class="btn btn-outline-success my-2 my-sm-0">Ingresar222</button>-->
                </form>
    
                    {% if form.non_field_errors  %}
                                <ul class="messages">
                                <li class="warning">
                                    Combinacion de credenciales incorrecta.
                                </li>
                                </ul>     
                    {% endif %}
            </div>
        {% endif %}
        
        
      </div>
    </nav>
    <main style="display: flex; justify-content: center; align-items: center; flex-direction: column; height: 100vh;">
      <h1>Bienvenido al sitio de HICAST</h1>
      <p>Esta es la página de ingreso a los Análisis.</p>
      <img src="{% static 'hicast/img/imagen.avif' %}" alt="Descripción de la imagen" style="margin-top: 20px; max-width: 100%; max-height: 80%; object-fit: contain;">
    </main>
  </div>
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#config-web-app -->
  <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.4.0/js/bootstrap4-toggle.min.js"></script>
  
  <script src="{% static 'hicast/js/app.js' %}"></script>
  <button id="miBoton" style="display: none;">Ir a la siguiente página</button>
  <button id="btnIR" type="button" class="btn btn-danger" onclick="cerrar()"  style="display: none;">Cerrar PRUEBA</button>
  </body>

</html>

aplicaciones/base_principal/templates/menulateral.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Inicio</div>
                <a class="nav-link" href="{% url 'base_principal:index' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Eventos
                </a>
                
                {% if sucursales %}
                <div class="sb-sidenav-menu-heading">CCN GLOBAL</div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuSucursales" aria-expanded="false" aria-controls="menuSucursales">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Sucursales
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuSucursales" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'ofertas:OfertasNacionales' %}">Crear</a>
                        <a class="nav-link" href="{% url 'sucursales:SucursalesListar' %}">Listar</a>
                    </nav>
                </div>
                {% endif %}
                
                <div class="sb-sidenav-menu-heading">Congregación</div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuMinisterio" aria-expanded="false" aria-controls="menuMinisterio">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Ministerio
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuMinisterio" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        {% if user.admin %}
                            <a class="nav-link" href="{% url 'peticiones:PeticionCrear' %}">Agregar Ministerio</a>
                            {% endif %}
                            <a class="nav-link" href="{% url 'peticiones:PeticionListar' %}">Listar Ministerios</a>
                    </nav>
                </div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuInventario" aria-expanded="false" aria-controls="menuInventario">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Inventario
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuInventario" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">

                            <a class="nav-link" href="{% url 'peticiones:PeticionCrear' %}">Crear Petición</a>
                        
                        <a class="nav-link" href="{% url 'peticiones:PeticionListar' %}">Listar Peticiones</a>
                    </nav>
                </div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuEstadisticas" aria-expanded="false" aria-controls="menuEstadisticas">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Estadisticas
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuEstadisticas" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">

                            <a class="nav-link" href="{% url 'peticiones:PeticionCrear' %}">Verificar Datos</a>
                        
                        <a class="nav-link" href="{% url 'peticiones:PeticionListar' %}">Listar Peticiones</a>
                    </nav>
                </div>

                <div class="sb-sidenav-menu-heading">Discipulado</div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuDiscipulados" aria-expanded="false" aria-controls="menuDiscipulados">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Discipulos
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuDiscipulados" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'discipulado:agregar_discipulos' %}">Agregar Discipulo</a>
                        <a class="nav-link" href="{% url 'discipulado:lista_discipulos' %}">Listar Discupulos</a>
                        <a class="nav-link" href="{% url 'discipulado:AsignarAsistenciasDiscipulado' %}">Asistencia</a>
                    </nav>
                </div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuReportes" aria-expanded="false" aria-controls="menuReportes">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Reportes
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuReportes" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        
                        <a class="nav-link" href="{% url 'productos:ProductoListar' %}">Listar Reportes</a>
                    </nav>
                </div>




                <div class="sb-sidenav-menu-heading">Servicios</div>

                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#menuAsistencias" aria-expanded="false" aria-controls="menuAsistencias">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Asistencias
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="menuAsistencias" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'servicio_congregacional:AsignarAsistencias' %}">Agregar Asistencias</a>
                        <a class="nav-link" href="{% url 'servicio_congregacional:AsignarAsistencias' %}">Detalles</a>
                    </nav>
                </div>

                

               

                <!-- 
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Categorias
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="login.html">Login</a>
                                <a class="nav-link" href="register.html">Register</a>
                                <a class="nav-link" href="password.html">Forgot Password</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                            Error
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="401.html">401 Page</a>
                                <a class="nav-link" href="404.html">404 Page</a>
                                <a class="nav-link" href="500.html">500 Page</a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Charts
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Tables
                </a>
            -->
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Bienvenido:</div>
            <span>{{user.username|title}}</span>
        </div>
    </nav>
</div>

aplicaciones/base_principal/templates/menusuperior.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'base_principal:index' %}">CCN
    </a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Buscar..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <div class="dropdown">
        <button type="button" class="badge rounded-pill bg-light text-dark position-relative" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
              </svg>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              99+
              <span class="visually-hidden">mensajes no leídos</span>
            </span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="#">Notificacion 1</a></li>
            <li><a class="dropdown-item" href="#">Notificacion 2</a></li>
            <li><a class="dropdown-item" href="#">Notificacion 3</a></li>
          </ul>

    </div>
    





    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'usuarios:perfil' %}">Perfil</a></li>
                <li><a class="dropdown-item" href="#">Actividades</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{% url 'login:logout' %}">Cerrar Sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>